# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16KXaDQhOcgxcF2xzHrJHtfAUwWO2QfjG
"""

sets={
    "00": {"ru": None, "data": [None, None]},
    "01": {"ru": None, "data": [None, None]},
    "10": {"ru": None, "data": [None, None]},
    "11": {"ru": None, "data": [None, None]}
}

def update(addr, setno):
  global sets
  if sets[setno]["ru"]==None:
    print("Miss")
    sets[setno]["data"][0]=addr
    sets[setno]["ru"]=0
  else:
    if addr in sets[setno]["data"]:
      print("Hit")
      # print("before", sets[setno]["ru"])
      sets[setno]["ru"]=sets[setno]["data"].index(addr)
      # print("after", sets[setno]["ru"])
    else:
      print("Miss")
      # print("before", sets[setno]["ru"])
      upind=1-sets[setno]["ru"]
      sets[setno]["data"][upind]=addr
      sets[setno]["ru"]=upind
      # print("after", sets[setno]["ru"])

dummy=["000001110000", "000010000000", '000001101000', '000110010000', '000010000100', '000101111000', '000010001100', '111100000000']

for i in dummy:
  addr=i[:-5]
  ind=i[-7:-5]
  update(addr, ind)
  print(addr)
  print(ind)
  print(sets)
  print()