# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A5XDlSYEYOYYwMd4XqJpOjDOk21H1TXK
"""

table={
    "LD": '000',
    "ST": '001',
    "ADD": '010',
    "SUB": '011',
    "ADDI": '100',
}

array_table={
    "a0": '000',
    "a1": '001',
    "a2": '010',
    "a3": '011',
    "a4": '100'
}

reg_table={
    "r0": '000',
    "r1": '001',
    "r2": '010',
    "r3": '011',
    "r4": '100'
}

def convert(instruction):
    writef=open('bin.txt', 'a')
    instr=instruction.split()
    print(instr)
    binins=[table[instr[0]]]
    if instr[0] == 'LD':
      binins.append(array_table[instr[1]])
      buff=bin(int(instr[2]))[2:]
      if len(buff)<3:
        while len(buff)<3:
          buff='0'+buff
      binins.append(buff)
      for i in range(int(instr[2])):
        buff=bin(int(instr[i+3]))[2:]
        if len(buff)<3:
          while len(buff)<3:
            buff='0'+buff
        binins.append(buff)
    if instr[0]=='ADD' or instr[0]=='SUB':
      binins.append(array_table[instr[1]])
      binins.append(array_table[instr[2]])
      binins.append(array_table[instr[3]])
    if instr[0]=='ADDI':
      binins.append(array_table[instr[1]])
      binins.append(array_table[instr[2]])
      buff=bin(int(instr[3]))[2:]
      if len(buff)<3:
        while len(buff)<3:
          buff='0'+buff
      binins.append(buff)
    if instr[0]=='ST':
      buff=bin(int(instr[1][0]))[2:]
      if len(buff)<3:
        while len(buff)<3:
          buff='0'+buff
      binins.append(buff)
      binins.append(array_table[instr[1][2:-1]])
      binins.append(reg_table[instr[2]])

    binstr=''
    for i in binins:
      binstr=binstr+str(i)
    print(binstr)
    writef.write(binstr)
    writef.write('\n')

    # print(binins)


f = open('instructions.txt', 'r')
for i in f:
  convert(i)

arr_sim={
    '000':[],
    '001':[],
    '010':[],
    '011':[],
    '100':[],
}

reg_sim={
    '000':0,
    '001':0,
    '010':0,
    '011':0,
    '100':0,
}

f=open('bin.txt', 'r')
arrays=[]
for istr in f:
  iarr=[istr[i:i+3] for i in range(0, len(istr), 3)]
  iarr.pop()
  print(iarr)
  if iarr[0]=='000':
    n=int(iarr[2], 2)
    buff=[]
    for i in range(n):
      buff.append(int(iarr[3+i], 2))
    arr_sim[iarr[1]]=buff
  if iarr[0] == '010':
    for i in range(len(arr_sim[iarr[2]])):
      arr_sim[iarr[1]].append(arr_sim[iarr[2]][i]+arr_sim[iarr[3]][i])
  if iarr[0] == '011':
    for i in range(len(arr_sim[iarr[2]])):
      arr_sim[iarr[1]].append(arr_sim[iarr[2]][i]-arr_sim[iarr[3]][i])
  if iarr[0]== '100':
    x=int(iarr[3], 2)
    for i in range(len(arr_sim[iarr[2]])):
      arr_sim[iarr[1]].append(arr_sim[iarr[2]][i]+x)
  if iarr[0]=='001':
    # print(int(iarr[1], 2))
    index=int(iarr[1], 2)//4
    reg_sim[iarr[3]]=arr_sim[iarr[2]][index]

print(arr_sim)
print(reg_sim)